apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample
    app.kubernetes.io/part-of: load-app-846d55d4-793e-41bd-aedb-666c5654da57
  name: devfile-sampleesan
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample
    weight: null
status: {}
